apiVersion: v1
kind: Service
metadata:
  name: genesis-service
spec:
  selector:
    app: genesis-service
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genesis-service
spec:
  selector:
    matchLabels:
      app: genesis-service
  replicas: 4
  template:
    metadata:
      labels:
        app: genesis-service
    spec:
      containers:
      - name: genesis-service
        image: bigpeegee/genesis:armv7
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
