apiVersion: v1
kind: ReplicationController
metadata:
  name: genesis-service
spec:
  replicas: 1
  selector:
    app: genesis-service
  template:
    metadata:
      labels:
        app: genesis-service
      name: genesis-service
    spec:
      containers:
      - name: genesis-service
        image: bigpeegee/genesis:demo
        imagePullPolicy: Always

